### ISSUE TITLE
Building on Ubuntu manually

### ISSUE THREAD

**Issue by bretty-mcbrettface** [vrothberg/vgrep#101]
What paths or variables am I missing? Make build just gives me errors like:

```
vgrep.go:25:2: cannot find package "github.com/jessevdk/go-flags" in any of:
        /usr/lib/go-1.10/src/github.com/jessevdk/go-flags (from $GOROOT)
```

I'm not super familiar with the go ecosystem, I assume it's something like `go get ...`?

**Comment by vrothberg** [comment]
Thanks for reaching out, @bretty-mcbrettface!

go 1.10 is pretty old already and I believe it already hit EOL. Go projects are now easier to build as there's now a notion of `go modules`. If you want to use go 1.10, however, you need place the project in `$GOPATH/go/src/github.com/vrothberg/vgrep`. Using later versions, it will build anywhere.

**Comment by vrothberg** [comment]
Please let me know if that worked for you.

**Comment by bretty-mcbrettface** [comment]
Got it, thanks. For future Ubuntu 18 users, go has to be installed via snap and not via apt (only has 1.10).

**Comment by vrothberg** [comment]
Great, thanks for checking!
