### ISSUE TITLE
Provide binary downloads?

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#116]
I'm aware that vgrep is already distributed to several package management solutions. Is there a reason why binaries couldn't be published here? 
I'm happy to add [goreleaser](https://goreleaser.com/) support if you find it useful. Additionally, this would allow others to use vgrep with [bin](https://github.com/marcosnils/bin)

**Comment by vrothberg** [comment]
Sounds great. Thanks, @marcosnils!

Feel free to open a PR :+1:

**Comment by vrothberg** [comment]
I finally did it. [v2.4.0](https://github.com/vrothberg/vgrep/releases/tag/v2.4.0) has binary downloads.

Thanks for kicking off the work :+1:
