### ISSUE TITLE
Seems like -A, -B and -C is broken in the latest release

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#118]
Seems like https://github.com/vrothberg/vgrep/issues/84 stopped working on the latest release. I'm getting stack traces errors or "failed to parse results" whenever I try to use one of those options.

**Comment by vrothberg** [comment]
Sorry for not getting back to you!

That was huge lack of coffee on my side as I closed https://github.com/vrothberg/vgrep/pull/88 instead of merging. The -A parsing was later tackled by @Qeole where we decided to error out.

I am still open to ignore non-matching lines (as long as we log them). @Qeole @marcosnils what do you think?

**Comment by marcosnils** [comment]
> I am still open to ignore non-matching lines (as long as we log them).

Hmmm.. I can't recall how this worked and I can't test it again since the branch has been removed. Do you mind sending the PR again and rebasing so I can try it out @vrothberg ?

**Comment by vrothberg** [comment]
> > I am still open to ignore non-matching lines (as long as we log them).
> 
> Hmmm.. I can't recall how this worked and I can't test it again since the branch has been removed. Do you mind sending the PR again and rebasing so I can try it out @vrothberg ?

Sure! Here's a PR to test: https://github.com/vrothberg/vgrep/pull/119

My work flow for displaying context lines is:
```
$ vgrep ...
$ vgrep -sc N
```

Would that work for you?

**Comment by vrothberg** [comment]
Ping @marcosnils. What do you think?

**Comment by marcosnils** [comment]
Just tried this... I'm not convinced about the UX though..

I'm still not sure why we can't do something like `vgrep -C 10 <search>` and output all the possible lines that you can jump to in vgrep's output as well.

**Comment by vrothberg** [comment]
> I'm still not sure why we can't do something like `vgrep -C 10 <search>` and output all the possible lines that you can jump to in vgrep's output as well.

#119 should do that. It's ignoring the separation lines though. Can you give an example how you would like it to look like?

**Comment by marcosnils** [comment]
> #119 should do that. It's ignoring the separation lines though. Can you give an example how you would like it to look like?

You're right.. seems like I was using the wrong version. I just have it another shot and I got this result

![image](https://user-images.githubusercontent.com/1578458/92002981-d95c7500-ed16-11ea-93eb-d6dc2fc0f425.png)

^ As you can see the output from standard grep and vgrep is a bit different, specially since it's missing some results that I get with grep. Is that expected?

**Comment by vrothberg** [comment]
Curious. I can't reproduce on Fedora. Are you on Mac OS?

**Comment by marcosnils** [comment]
Here's the debug output to see if that helps to see what could be happening. I can see some "failed to parse" which I think is the issue, correct?

![image](https://user-images.githubusercontent.com/1578458/92255691-12c4ea00-eea9-11ea-8b15-8e0086ba5c44.png)

**Comment by vrothberg** [comment]
Sorry for the longer silence! Busy times after a relocation.

I need some more time to think this through but I am always open to suggestions. It's a hairy issue and I don't want to break backwards compat.

On a positive note: there is a workaround by first doing `vgrep foo` follow by `vgrep -sc` (for showing context lines).

**Comment by vrothberg** [comment]
@marcosnils could you have another at https://github.com/vrothberg/vgrep/pull/119? It turned out that `git grep` and `grep`/`ripgrep` behave again slightly different which was causing the issue you saw with ripgrep.

If you're cool with the changes, I can wrap things up and cut a new release soon.

**Comment by marcosnils** [comment]
Sure, will check in a few mins

**Comment by marcosnils** [comment]
Works like charm @vrothberg :muscle: LGTM!

**Comment by vrothberg** [comment]
> Works like charm @vrothberg muscle LGTM! Preciate taking the time to check this

Thanks for testing and your patience!
