### ISSUE TITLE
add man pages

### ISSUE THREAD

**Issue by vrothberg** [vrothberg/vgrep#123]
I think it's time to add man pages to vgrep. As many other go projects, we can use [go-md2man](https://github.com/cpuguy83/go-md2man) and use markdown. The content can be borrowed from the README.

**Comment by vrothberg** [comment]
I'll open it for Hacktoberfest, and want to encourage participants to chose planting a tree rather than getting a t-shirt.

**Comment by vrothberg** [comment]
I want a simple setup, similar to [Skopeo](https://github.com/containers/skopeo) (and others containers/ tools).
`make docs` to generate the docs, and the necessary plumbing in `make install`.

**Comment by ahmedkrmn** [comment]
Hi @vrothberg,
Can I work on this one?

**Comment by vrothberg** [comment]
Sure! Thanks for reaching out!

**Comment by vrothberg** [comment]
@ahmedkrmn, how's it going?

**Comment by ahmedkrmn** [comment]
HI @vrothberg, I've submitted a PR to close this issue, please have a look at it.
Per the new [Hacktoberfest update](https://hacktoberfest.digitalocean.com/hacktoberfest-update), please label the PR as "hacktoberfest-accepted".
