### ISSUE TITLE
Version > 2.3.3 on Mac?

### ISSUE THREAD

**Issue by mrthebob** [vrothberg/vgrep#126]
Is it possible to install a version greater than 2.3.3 on Mac? I used Homebrew - looks like the latest is stuck at 2.3.3?

Thanks!

**Comment by vrothberg** [comment]
Thanks for reaching out, @mrthebob!

It looks like @alebcay is maintaining the Homebrew formula. @alebcay, are you the right person to talk to for updating the formula?

**Comment by vrothberg** [comment]
@mrthebob alternatively you could use the Mac Ports package or download the binary from the last release (https://github.com/vrothberg/vgrep/releases/tag/v2.4.0).
