### ISSUE TITLE
shell brakes on Ctrl-D

### ISSUE THREAD

**Issue by dasGringuen** [vrothberg/vgrep#14]
When exiting with Ctrl+D the shell doesn't go back to its default configuration

**Comment by vrothberg** [comment]
Hi Adrian,
thanks a lot for reporting the issue.  For me, nothing happens pressing CTRl+D, but +C left vgrep in a weird state.  less ignores it by default, so vgrep does the same now.

Commit 50e906dec392 should fix it.
