### ISSUE TITLE
Highlighting the searched pattern

### ISSUE THREAD

**Issue by jaybh** [vrothberg/vgrep#15]
I love your tool. It has improved my workflow considerably, considering it combines the speed of git grep, with ack's ability to filter files to search the pattern in.

Is there  a way to color code the matches in the "Content" column ?

Let me explain why that is useful:
1) Sometimes we don't remember the entire symbol name, so we tend to search only a partial symbol name. It's very difficult to locate that partial symbol in the matches, especially if there is more than even 5 results.

2) I kinda workaround this, by piping the output of vgrep to grep again since grep will color code the matches by default. So I have a hacky bash function like below:

v () 
{ 
    text="$1";
    shift;
    vgrep ${text} $@ | grep --color=auto ${text}
}

But since grep does not output to less, this breaks down when the list of matches is greater than my scroll window.

It would be much cleaner to implement highlighting the pattern match in vgrep's output itself.

**Comment by vrothberg** [comment]
Hi Jay,

thanks a lot, it makes me really happy to hear that vgrep helps other people than me to get their work done :)

There's a way to color the content matches as well.  I haven't implemented it yet, but I guess it won't be a big change.  In case it's slowing down too much (strings are really expensive in Python), I will make it optional.

Thanks for your interest.

Best regards,
  Valentin

**Comment by vrothberg** [comment]
Hi Jay,

I played a little bit around and pushed the change.  You can test the new highlighting on the master branch.  Please let me know if it works for you as expected.

Kind regards,
 Valentin

**Comment by jaybh** [comment]
Thanks a lot. i will try it out and get back to you.

**Comment by jaybh** [comment]
Your latest changes do implement what I am looking for. I profiled the tool with and without the highlighting expense:

```bash
sync; echo 1 > /proc/sys/vm/drop_caches # Clear cache
time vgrep locked /src/linux/kernel &>/dev/null # Time it with highlighting - returns 1.36 seconds

sync; echo 1 > /proc/sys/vm/drop_caches  # Clear cache
time vgrep locked /src/linux/kernel &>/dev/null # Time it without highlighting - returns 1.28 seconds
```

So, although there is a bit of a difference, its tolerable for small projects. 
Best to keep the feature by default, but provide a command line switch to disable it for performance.
