### ISSUE TITLE
"All" selector not working?

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#165]
IIUC from this example (https://github.com/vrothberg/vgrep#more-commands-and-the-interactive-shell) I could use an "all" selector to edit all the matched expressions, is that correct? I'm getting a "unsupported command 'all'" when trying to use that. 

```
$ vgrep -s all
unsupported command "all"
```

Am I missing something here?

**Comment by vrothberg** [comment]
Thank you for reaching out, @marcosnils!

That's possible a regression when porting vgrep from python to go a couple of years ago.  Interested in opening a PR?

**Comment by marcosnils** [comment]
Sure, will send a fix today.

**Comment by vrothberg** [comment]
Are you still interested? If you don't find time, no problem at all. I can take over if needed.

**Comment by marcosnils** [comment]
Hey Valentin,

Still interested but have very little time TBH. Please go ahead and take it
over if you have the time to work on it.

Cheers!

**Comment by vrothberg** [comment]
Thanks, I tracked it down to a malformed regex. It's working now :)
