### ISSUE TITLE
vgrep failed randomly on fedora 35

### ISSUE THREAD

**Issue by mylabzhen** [vrothberg/vgrep#176]
vgrep work normally before today，but failed with no output now.

~  which vgrep                                                                                                                                         1 х │ root@fedora │ 16:12:40
vgrep='vgrep --interactive'
	/usr/bin/vgrep
 ~  vgrep --interactive                                                                                                                                   
 ~  vgrep -d                                                                                                                                            
DEBU[0000] log level set to debug
DEBU[0000] passed args: []
DEBU[0000] loadCache(): start
DEBU[0000] loadCache(): end

**Comment by mylabzhen** [comment]
Yes, i tried install from source vgrep-2.6.0

**Comment by vrothberg** [comment]
Can you share a reproducer? I fail to reproduce:
```
$ podman run --rm -it fedora:35 bash
[root@3075fc927710 /]# dnf install git vgrep -y -q
[root@3075fc927710 vgrep]# vgrep --version
2.5.1
[root@3075fc927710 /]# git clone https://github.com/vrothberg/vgrep.git; cd vgrep
[root@3075fc927710 vgrep]# vgrep Valentin
Index File                                          Line Content
    0 internal/ansi/ansi.go            5 // (c) 2017 Valentin Rothberg <valentinrothberg@gmail.com>
    1 internal/colwriter/colwriter.go  7 // (c) 2017 Valentin Rothberg <valentinrothberg@gmail.com>
    2 test/simple.bats                68 run_vgrep --files-with-matches Valentin vgrep.go
    3 vgrep.go                         3 // (c) 2015-2022 Valentin Rothberg <valentin@rothberg.emai>
[root@3075fc927710 vgrep]# vgrep --interactive
Enter a vgrep command: 
```

**Comment by mylabzhen** [comment]
~/linux │ v5.14  dnf install git vgrep -y -q                                                                                                        
Installed:
  vgrep-2.5.1-3.fc35.x86_64

 ~/linux │ v5.14  vgrep --interactive                                                                                                                                                                                                                                             
 ~/linux │ v5.14  vgrep Valentin                                                                                                                    
Index File                                                                                       Line Content
    0 Documentation/admin-guide/media/si4713.rst                                   10 Contact: Eduardo Valentin <eduardo.valentin@nokia.com>
    1 Documentation/process/kernel-enforcement-statement.rst                      153 - Eduardo Valentin (Amazon.com)

**Comment by mylabzhen** [comment]
I reproduce this problem in Centos 8.
Execute vgrep --interactive firstly after go build, no output.
Execute vgrep no.
After that vgrep --interactive recover normal.

**Comment by vrothberg** [comment]
Thanks a lot for checking. Feel free to reopen in case there's another problem.
