### ISSUE TITLE
vgrep looking for path to executable in $EDITOR and failing 

### ISSUE THREAD

**Issue by suvayu** [vrothberg/vgrep#178]
It seems `vgrep` expects `EDITOR` to point to an executable (a path) rather than a command.  I run Emacs in daemon mode, and always use it from the terminal, so for me it is set to: `emacsclient -nw -a=""`, and `vgrep` fails with:

    exec: "emacsclient -nw -a=\"\"": executable file not found in $PATH

I would expect a behaviour equivalent to: `$EDITOR <options>`, not `"$EDITOR" <options>`.

**Comment by vrothberg** [comment]
Thanks for reaching out, @suvayu!

> It seems `vgrep` expects `EDITOR` to point to an executable (a path) rather than a command.

It can be both, a path and a command.

> I would expect a behaviour equivalent to: `$EDITOR <options>`, not `"$EDITOR" <options>`.

I did some research on the web but could not find a standard that would define whether arguments should be passed via that variable.  But I think it's a reasonable request.

**Comment by vrothberg** [comment]
Thanks for sharing, @suvayu!

Are you interested in contributing?  In order to support your request, the EDITOR value had to be parsed (e.g., via `github.com/google/shlex).  An additional test should make sure we won't regress in the future.

**Comment by suvayu** [comment]
Thanks for urging me to contribute (and the hint).  I have never written go, this gives me an incentive :).  I'll submit a PR over the weekend.

**Comment by vrothberg** [comment]
Awesome, thanks a lot, @suvayu!

Make sure to run `make vendor` to pull in the new dependency before committing the changes.
