### ISSUE TITLE
more interactive experience in fish shell

### ISSUE THREAD

**Issue by DhruvaG2000** [vrothberg/vgrep#186]
I am using a fish shell and it seems like adding the following chunk:

```sh
function vgrep
set INITIAL_QUERY $1
set VGREP_PREFIX "vgrep --no-header "
set FZF_DEFAULT_COMMAND "$VGREP_PREFIX '$INITIAL_QUERY'" \
fzf --bind "change:reload:$VGREP_PREFIX {q} || true" --ansi --phony --tac --query "$INITIAL_QUERY" \
| awk '{print $1}' | xargs -I{} -o vgrep --show {}
end
```
Doesn't seem to do anything. After adding this vgrep just does nothing ie. no output for even ``vgrep --help``

**Comment by vrothberg** [comment]
Thank you for reaching out.  I am unfamiliar with fish shell but maybe the fzf experts can help (@michaeladler @SuperSandro2000).

**Comment by SuperSandro2000** [comment]
That works for bash. No clue what fish does different.

**Comment by vrothberg** [comment]
Thanks for checking, @SuperSandro2000!

**Comment by SanchayanMaity** [comment]
@DhruvaG2000 Here are the two functions in fish which I have

```
function vgf --wraps=vgrep --description 'vgrep search with fzf'
    set -f INITIAL_QUERY $argv[1]
    vgrep --no-header $INITIAL_QUERY | fzf --ansi --bind "Ctrl-d:half-page-down,Ctrl-u:half-page-up" | awk '{print $1}' | 
    xargs -I{} -o vgrep --show {}
end
```

```
function vgF --wraps=vgrep --description 'vgrep search with fzf'
    set -f INITIAL_QUERY $argv[1]
    FZF_DEFAULT_COMMAND="vgrep --no-header $INITIAL_QUERY" fzf --bind "Ctrl-d:half-page-down,Ctrl-u:half-page-up,change:reload:vgrep --no-header {q} || true" --ansi --phony --tac --query $INITIAL_QUERY | awk '{print $1}' | xargs -I{} -o vgrep --show {}
end
```

**Comment by vrothberg** [comment]
Thanks a lot for sharing, @SanchayanMaity !

**Comment by DhruvaG2000** [comment]
Thanks @SanchayanMaity , this helped me alot!
@vrothberg , can we add this to the README under the last fzf section specifying "for fish"?

**Comment by vrothberg** [comment]
Sure, @DhruvaG2000 !  Would you open a pull request for it?

**Comment by SanchayanMaity** [comment]
@vrothberg  I created a PR.
