### ISSUE TITLE
free(): double free detected in tcache 2 

### ISSUE THREAD

**Issue by claudiubeznea** [vrothberg/vgrep#196]
Hi,

I'm getting this message every time I'm trying to vgrep.
I'm running in Ubuntu 23.04 on top of this commit:

commit 315676f5164fc9a5c9d3a46069396a591703d561 (HEAD -> main, origin/main, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Jul 10 04:25:00 2023 +0000

    build(deps): bump golang.org/x/term from 0.9.0 to 0.10.0
    
    Bumps [golang.org/x/term](https://github.com/golang/term) from 0.9.0 to 0.10.0.
    - [Commits](https://github.com/golang/term/compare/v0.9.0...v0.10.0)
    
    ---
    updated-dependencies:
    - dependency-name: golang.org/x/term
      dependency-type: direct:production
      update-type: version-update:semver-minor
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>

free(): double free detected in tcache 2
Aborted (core dumped)

Is this something known?

Thank you,
Claudiu

**Comment by vrothberg** [comment]
Thanks for reaching out, @claudiubeznea!

> Is this something known?

No, that's the first time I hear about it.  I just built the referenced commit in an Ubuntu 23.04 container but could not reproduce the issue.

**Comment by vrothberg** [comment]
@claudiubeznea, are you still seeing the issue?

**Comment by claudiubeznea** [comment]
@vrothberg : yes, the issue is still there. However I haven't updated vgrep tree. If you don't see it maybe there is some prerequisites libraries that I'm missing? Are there some dependencies? On my previous system vgrep used to work out of the box.

Thank you,
Claudiu

**Comment by vrothberg** [comment]
> If you don't see it maybe there is some prerequisites libraries that I'm missing?

No external libraries are needed to build `vgrep`.  Did you update your Ubuntu to the latest updates?  Maybe there's a bug somewhere.  As mentioned above, I built vgrep in a 23.04 container and it worked, so I am a bit puzzled.

**Comment by claudiubeznea** [comment]
@vrothberg : yes, I have the Ubuntu 23.04 updated. It is still not working on my side.

**Comment by vrothberg** [comment]
@claudiubeznea thanks for checking.

I really don´t know what's going on.  I tested in a container and double-checked in a fresh 23.04 VM but cannot reproduce.  Did you install a custom go toolchain or do you use the official golang packages in Ubuntu?

**Comment by claudiubeznea** [comment]
I'm using the default instalation. I haven't installed anything related to go.

**Comment by claudiubeznea** [comment]
I'm closing this one as I'm no longer running in a VM and I have no more issues. Thank you for your support.
