### ISSUE TITLE
Question only: where does vgrep store information of previous search?

### ISSUE THREAD

**Issue by paxsali** [vrothberg/vgrep#199]
Hi all,

I only have a question about how `vgrep --show N` works, where N is the index (integer) of the previous search results table.

It's probably not in the environment (or I didn't find it there), so how does vgrep do it? I'm baffled how it works.

Does it store temporary files?

There is nothing mentioned in the documentation or README.MD.

(And yes, I didn't look at the source code, because I don't know go, tbh...)

Please provide an explanation.

Thank you.

**Comment by vrothberg** [comment]
Hi @paxsali,

thanks for reaching out.  There is clearly a lack of documentation that should be addressed; users shouldn't need to read the code.

> Does it store temporary files?

Yes, `vgrep` maintains a cache of the _last query_.  So `vgrep foo` stores the results such that a subsequent `vgrep` will use the cached results.

The path to the cache is `$LOCALAPPDATA/vgrep-cache/vgrep-go` on Windows and `$HOME/.cache/vgrep-go` on Unix systems.  The format of the file is JSON.

Hope that helps.
