### ISSUE TITLE
When ripgrep is installed, vgrep exits when a file with no read access is in the directory

### ISSUE THREAD

**Issue by inknos** [vrothberg/vgrep#216]
**Reproducer:**

1. Install `vgrep` and `ripgrep`
2. Clone `vgrep` and `cd` into it
3. Run `sudo touch sudofile`
3.1. 
   ```
   ls -l sudofile 
   -rw-r--r--. 1 root root 0 16. kvě 17.31 sudofile
   ```
4. Run `sudo chmod o-r sudofile`
4.1. 
   ```
   ls -l sudofile 
   -rw-r-----. 1 root root 0 16. kvě 17.31 sudofile
   ```
5. Run `vgrep something`

**Results:**

`searching symbols failed: rg: sudofile: Permission denied (os error 13) [rg]`

**Expected results:**

```
Index File                                             Line Content
    0 vendor/github.com/jessevdk/go-flags/flags.go       67 Then, the AuthorInfo map can be filled with something like
    1 vendor/github.com/sirupsen/logrus/logger.go        20 // something more adventurous, such as logging to Kafka.
    2 vendor/github.com/sirupsen/logrus/README.md       253 requestLogger.Info("something happened on that request") # will log request_id and user_>
    3 vendor/github.com/sirupsen/logrus/README.md       254 requestLogger.Warn("something not great happened")
    4 vendor/github.com/sirupsen/logrus/README.md       347 // do something here to set environment depending on an environment variable
    5 vendor/github.com/sirupsen/logrus/README.md       494 // gracefully shutdown something...
    6 vendor/github.com/modern-go/concurrent/README.md
```

**Versions:**
$ rpm -q vgrep
vgrep-2.6.1-3.fc39.aarch64
$ rpm -q ripgrep
ripgrep-14.1.0-2.fc39.aarch64

**Additional information:**

Uninstalling `ripgrep` fixes it. I did some digging and [these](https://github.com/vrothberg/vgrep/blob/main/vgrep.go#L330-L331) look like the offending lines. I don't know go much though, so I don't know how to fix it from the top of my head :)

It would be nice to see this fixed, especially because running it [like in the README](https://github.com/vrothberg/vgrep/blob/main/README.md?plain=1#L84-L92) leads to `[Command failed: vgrep --no-header  'something']` and it does not really say what's wrong.

**Comment by vrothberg** [comment]
Thanks for reaching out, @inknos !  Always happy to see vgrep being used in the wild :)

Without ripgrep vgrep will try to use git-grep which does not fail when the sudofile hasn't been committed yet.  I tried it with --no-ripgrep which also works because vgrep uses git-grep. Adding the --no-git flag will then fail again, because vgrep will then use grep.

What vgrep could do is to parse stdout even in case of an error, and report the error with the same exit code as the underlying grep implementation.

**Comment by vrothberg** [comment]
@inknos, do you have time to test PR https://github.com/vrothberg/vgrep/pull/217?  This should address the issue.
