### ISSUE TITLE
build dependencies are not specified anywhere

### ISSUE THREAD

**Issue by gregkh** [vrothberg/vgrep#27]
I might be missing some documentation somewhere, but when trying to build I get the following dependency error:

    $ make build
    go build -o ./build/vgrep -ldflags "-s -w -X main.version=2.0.0-bd35a5e9228a464b873f922f3b82db5c1da918f7-dev"
    vgrep.go:20:2: cannot find package "github.com/jessevdk/go-flags" in any of:
            /usr/lib/go/src/github.com/jessevdk/go-flags (from $GOROOT)
            /home/gregkh/go/src/github.com/jessevdk/go-flags (from $GOPATH)
    vgrep.go:21:2: cannot find package "github.com/sirupsen/logrus" in any of:
            /usr/lib/go/src/github.com/sirupsen/logrus (from $GOROOT)
            /home/gregkh/go/src/github.com/sirupsen/logrus (from $GOPATH)
    vgrep.go:22:2: cannot find package "github.com/vrothberg/vgrep/ansi" in any of:
            /usr/lib/go/src/github.com/vrothberg/vgrep/ansi (from $GOROOT)
            /home/gregkh/go/src/github.com/vrothberg/vgrep/ansi (from $GOPATH)
    vgrep.go:23:2: cannot find package "github.com/vrothberg/vgrep/colwriter" in any of:
            /usr/lib/go/src/github.com/vrothberg/vgrep/colwriter (from $GOROOT)
            /home/gregkh/go/src/github.com/vrothberg/vgrep/colwriter (from $GOPATH)
    make: *** [Makefile:16: build] Error 1

Any hints as to what needs to be included in the build system?

**Comment by darnir** [comment]
I raised a similar issue with #26.

Apparently a bunch of Go packages are required to build `vgrep` and the toolchain doesn't automatically pull them in. Apparently there is a `go get ./..` or similar command which could be used. But I'd like to be able to enumerate the dependencies explicitly.

**Comment by vrothberg** [comment]
@gregkh Thanks a lot for taking your time to report the issue. As @darnir mentioned, there's already issue #26 , so I will close this one. I extended the README with some explanations.

What I suggest doing is either using `make buildInContainer` which sets up everything or to place your vgrep source tree in `$GOPATH/src/github.com/vrothberg/vgrep`. Use `make build` to compile without checks or `make release`, which sets the version as specified in the `VERSION` file.

**Comment by gregkh** [comment]
`make buildInContainer` works great for me, thanks for that!
