### ISSUE TITLE
Need to eliminate things related to old `-w` options

### ISSUE THREAD

**Issue by Taeung** [vrothberg/vgrep#30]
Hi @vrothberg 😄 
`vgrep` looks great tool !!

But I saw the description and example regrading `-w` option,
I thought it is because of the`-w` option from 46db0da,
however, it is removed at 6385bab , right ?

So I suggest modifying some parts of README.md on
https://github.com/vrothberg/vgrep/blob/master/README.md#searching-patterns

**Comment by vrothberg** [comment]
Hi @Taeung, thanks! That's more or less just a coincidence. The text mentioning the `-w` relates to the fact that all non-vgrep options will be passed along to (git-) grep. So a `vgrep -w foo` will invoke `git-grep -w foo` and hence only search for foo at word boundaries. I used the `-w` option as an example as it is a common use case for textual searches.

See the README: "All non-vgrep flags and arguments will be *passed along to either grep or git-grep*. The command $vgrep -w foo, for instance, will only print matching lines where foo forms a whole word as the *-w flag will be passed to grep or git-grep.*"

**Comment by Taeung** [comment]
Oh.. I got it 😄

**Comment by vrothberg** [comment]
Great :-) Thanks a lot for taking the time to report!

**Comment by Taeung** [comment]
@vrothberg , However, currently `vgrep -h` don't have a description of the `-w` option like below.
Isn't also needed to add the description ? 
```
$ vgrep -h
Usage:
  vgrep [OPTIONS]

Application Options:
  -d, --debug             Verbose debug logging
  -i, --interactive       Enter interactive shell
      --no-git            Use grep instead of git-grep
      --no-header         Do not print pretty headers
      --no-less           Use stdout instead of less
  -s, --show=SELECTORS    Show specified matches or open shell
  -v, --version           Print version number

Help Options:
  -h, --help              Show this help message
```

**Comment by vrothberg** [comment]
@Taeung, I don't think so, because it is not an option of `vgrep` but one of `grep` and `git-grep`. As the `-w` is not a vgrep option, it just passed along to execute grep. In other words, it is interpreted as input, not as an option, just as "foo" is an input in `vgrep foo`.

**Comment by Taeung** [comment]
Oh..I confused it.. :)
