### ISSUE TITLE
vgrep -i flag conflicts with existant grep -i flag 

### ISSUE THREAD

**Issue by nbenitez** [vrothberg/vgrep#62]
I just installed vgrep, then procceed with a `vgrep -i somesymbol` and returned (wrongly) no matches, then I found out vgrep has also a `-i` flag, but I need the grep `-i` flag (for case insensitive search) because by default vgrep does case sensitive searches.

**Comment by vrothberg** [comment]
Hi @nbenitez, thanks for reaching out! I opened #63 to address the issue by dropping `-i`. Feel free to drop a comment on #63.

**Comment by nbenitez** [comment]
I just tested the fix and it works correctly, thank you :-).
