### ISSUE TITLE
Feature Request: More Interactive with selector

### ISSUE THREAD

**Issue by tjmtmmnk** [vrothberg/vgrep#67]
Thanks for creating a great tool!

But, I felt a little inconvenient to manipulate the search results.

- Now I need to run `vgrep` and then `vgrep --show` with the matching line
- It's a little inconvinient
- Therefore, I propose that the search results can be operated with the arrow keys.

(sorry for my poor English)

**Comment by vrothberg** [comment]
Hi @tjmtmmnk,

thanks for reaching out!

> Therefore, I propose that the search results can be operated with the arrow keys.

I want to keep vgrep as simple as possible. Implementing a pager is hard to get right and would increase the complexity quite substantially.

However, such tool already exists and funnily has the same name:
https://hackage.haskell.org/package/vgrep

**Comment by tjmtmmnk** [comment]
@vrothberg 

> I want to keep vgrep as simple as possible. Implementing a pager is hard to get right and would increase the complexity quite substantially.

I got it. I also agree that implementing paging will be complicated...

> However, such tool already exists and funnily has the same name:
https://hackage.haskell.org/package/vgrep

Oh, I didn't know that tool. Thank you for your introduction!

I will close this Issue.
