### ISSUE TITLE
conflict with existing vgrep on ubuntu 18.04

### ISSUE THREAD

**Issue by lucas0** [vrothberg/vgrep#68]
Hello, I'm sorry if this is not a relevant question and it is not the right place to ask it but apparently there is already a vgrep in my ubuntu 18.04 instalation under /usr/bin and even though the installation of your vgrep goes with no errors, I guess the vgrep command is bound to the original vgrep.

`man vgrep` yields this:

NAME
       vgrep, vegrep, vfgrep - print lines matching a pattern

SYNOPOSIS
       vgrep [ vbind-options ] [ -[[AB] ]num ] [ -[CEFGVBchilnsvwx] ] [ -e ] pattern | -ffile ] [ names...  ]

DESCRIPTION
       Vgrep is GNU grep with a patch to access AtFS version objects.  Vgrep searches the files and AtFS version objects listed in the arguments (or standard input if no names are given, or the name - is given) for lines containing a match to the given pattern.  By default,
       vgrep prints the matching lines.

how can i bind `vgrep` to your vgrep? Do you see issues coming from doing this?

Thanks for your time and attention,
Lucas.

**Comment by vrothberg** [comment]
Hi @lucas0,

thanks for reaching out!

> how can i bind vgrep to your vgrep? Do you see issues coming from doing this?

Do you want to use the Ubuntu-vgrep's output for vgrep or are you concerned about the name conflict?

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by vrothberg** [comment]
Please re-open if there's anything I can do.
