### ISSUE TITLE
Flag -i conflicts with grep ignore case?

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#78]
`vgrep -i` conflicts with `grep -i` (ignore case) option. The only way I've found to ignore case while using it is using the long `--ignore-case` option.

**Comment by vrothberg** [comment]
Hi @marcosnils, thanks for reaching out!

The issue has been fixed with commit 0810837a928d078f3d3d01ed2c130a2e4b91a90d and released with vgrep v2.3.0. Are you using an older version of vgrep?

**Comment by marcosnils** [comment]
Indeed, just updated to the latest version and it has been fixed. Thx for that!
