### ISSUE TITLE
Add script for installation

### ISSUE THREAD

**Issue by NightMachinary** [vrothberg/vgrep#81]
Either a Homebrew package (they should work on both Linux and macOS), or a shell script. Sth one can copy and paste easily without thinking. It helps a lot to make one more enthused to try a new tool.

**Comment by vrothberg** [comment]
Thanks for the feedback, @NightMachinary!

On Mac OS, you can install vgrep via macports: https://ports.macports.org/port/vgrep/summary

Some Linux distributions are shipping vgrep (e.g., Arch, openSUSE). While I would love to increase the coverage, I do not have the time and hope for an organic growth. I am really happy about the macports and now hope that the new Windows package manager can help to spread vgrep there.

Other than that: `make build && sudo make install` are the current way to go.

I believe you're pointing in the direction to offer binaries along with each release?

**Comment by NightMachinary** [comment]
@vrothberg Unfortunately, `macports` somehow never gets installed on my machine. I have no idea why. Anyways, I think just putting a complete (git clone, make build, make install, if that's all) on the readme itself would help. If offering binaries, I think it'd be a good idea to put a little script on the readme that just downloads and links it to, e.g., `~/bin/`.
