### ISSUE TITLE
-l (list file matches) doesn't seem tow work

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#83]
vgrep -l <some_text>

Doesn't seem to be printing anything. IIUC the `files` selector should do the same thing, but I couldn't find a way to make it work as a one liner. I'd have expected to do something like `vgrep --no-header -s=files <some_textt>` and I'm getting: 
```
marcos:wl/clusters (master) $ vgrep --no-header -s=files test 
"files test" doesn't match format "command[context lines] [selectors]"```
```

ideas?

**Comment by vrothberg** [comment]
Thanks for opening the issue!

This scenario isn't supported, so we can't grep for text and open it in one command. The reasoning for that is to make using `--show` a bit more friendly and allow for `--show a b c` instead of `--show="a b c"` - following arguments are appended.
