### ISSUE TITLE
-v and --version to print version seems not to be working

### ISSUE THREAD

**Issue by marcosnils** [vrothberg/vgrep#85]
```
marcos:vrothberg/vgrep (master)$ vgrep -v

```
I assume it's been sent to `grep/git grep` instead..

**Comment by disposedtrolley** [comment]
It seems to be working for me

```
$ vgrep -v                                                                                                                                                   
2.3.0-41386d0ec6a7e5e33fe51fffb5d43d2f64dbe998-dev
```

Are you running the latest commit on `master` (`41386d0ec6a7e5e33fe51fffb5d43d2f64dbe998`)?

**Comment by vrothberg** [comment]
I assume that the `vgrep` binary wasn't build with the Makefile where the version isn't being set via the linker (see https://github.com/vrothberg/vgrep/blob/master/Makefile#L26).

Did you build it manually via `go build`?

**Comment by marcosnils** [comment]
That seems to be the case. I'm building the binary directly with `go build`.
