### ISSUE TITLE
Add option to install with `brew`

### ISSUE THREAD

**Issue by elazarl** [vrothberg/vgrep#90]
Hi,
For easier installation on Mac, ` brew install elazarl/homebrew-vgrep/vgrep`, I added the repository http://github.com/elazarl/homebrew-vgrep

Can you please fork this repository here, and mention it as a viable way to install vgrep on Mac?

**Comment by vrothberg** [comment]
Sounds great! Would you open a pull request here? I'm not sure whether you want a make target, add a link in the readme or add the brew formula here. I am okay with all of them.

**Comment by rwhogg** [comment]
`vgrep` is now available in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/57569

**Comment by vrothberg** [comment]
> `vgrep` is now available in homebrew-core: [Homebrew/homebrew-core#57569](https://github.com/Homebrew/homebrew-core/pull/57569)

Thanks! I'll add that to the README.

**Comment by yermulnik** [comment]
Is here anyone familiar with Homebrew? I'm willing to add Linux bottle support to the Formulae, though I don't know how (Homebrew docus are quite convoluted when it gets to the questions like this).
https://github.com/Homebrew/homebrew-core/pull/57569#issuecomment-958948585

**Comment by yermulnik** [comment]
JFYI: this repo has Linux binaries which means there's not impediments for Linux builds and also Homebrew build-from-source works fine
```
> brew install --build-from-source vgrep
==> Downloading https://ghcr.io/v2/homebrew/core/go-md2man/manifests/2.0.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go-md2man/blobs/sha256:8b39e17cacacb31eecfc3412dd251b536c717384c463
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:8b39e17cacacb31eecfc3412dd251b5
######################################################################## 100.0%
==> Downloading https://github.com/vrothberg/vgrep/archive/v2.5.5.tar.gz
==> Downloading from https://codeload.github.com/vrothberg/vgrep/tar.gz/v2.5.5
# #=O#- #
==> Installing dependencies for vgrep: go-md2man
==> Installing vgrep dependency: go-md2man
==> Pouring go-md2man--2.0.1.x86_64_linux.bottle.tar.gz
✔  /home/linuxbrew/.linuxbrew/Cellar/go-md2man/2.0.1: 6 files, 2.0MB
==> Installing vgrep
==> make release
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5
✔  /home/linuxbrew/.linuxbrew/Cellar/vgrep/2.5.5: 6 files, 3.8MB, built in 3 seconds
```

**Comment by yermulnik** [comment]
@vrothberg Could you please take a look into the error in the test?
https://github.com/Homebrew/homebrew-core/pull/57569

**Comment by vrothberg** [comment]
@yermulnik, I don't see an error related to vgrep in https://github.com/Homebrew/homebrew-core/runs/4098452150?check_suite_focus=true.

**Comment by yermulnik** [comment]
@vrothberg And does this look related to `vgrep` or not? Thanks.
https://github.com/Homebrew/homebrew-core/runs/8061347335?check_suite_focus=true#step:7:38

**Comment by yermulnik** [comment]
Oh, please disregard. It seems to be not related to `vgrep` per se too 🤦🏻
Would it make sense to target build test to `testpath/"test.txt"` instead of current dir (`.`) to speed it up (in case test fails because of too any files/dirs in dir current to build)?

**Comment by vrothberg** [comment]
Thanks for reaching out, @yermulnik. It looks like brew has its own smoke tests for vgrep. You can also use `make test-integration`. Depending on the environment you can trim the tests down to `bats tests/simple.bats`.

**Comment by yermulnik** [comment]
I'm not sure about the env where Brew bottles are built, I was just trying to figure how the brew `test` could be quickly and easily fixed to allow `vgrep` to ve installed on Linux w/o a need to build locally: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vgrep.rb#L38-L43
So the easiest and quickest would be to test against the file created within `test` stage rather than against a directory recursively, right?

**Comment by vrothberg** [comment]
> So the easiest and quickest would be to test against the file created within `test` stage rather than against a directory recursively, right?

Yes, you can run `vgrep peanut ./test` for instance.
